# Rails 8.1 defaults initializer
#
# This file is intentionally conservative: it did not flip any defaults initially.
# In PR3 we enable a very small, low-risk subset of 8.1 defaults.
#
# Read the Guide for Upgrading Ruby on Rails for more info:
# https://guides.rubyonrails.org/upgrading_ruby_on_rails.html

# Enable safe subset of Rails 8.1 defaults (batch 1):
# - Track template render dependencies via Ruby parser (no behavior change for users)
Rails.configuration.action_view.render_tracker = :ruby

# - Omit autocomplete="off" on hidden fields generated by tag helpers
#   This only affects rendered attributes; no runtime behavior change.
Rails.configuration.action_view.remove_hidden_field_autocomplete = true

# Other 8.1 defaults to be evaluated in later PRs:
# Rails.configuration.active_record.raise_on_missing_required_finder_order_columns = true
# Rails.configuration.action_controller.action_on_path_relative_redirect = :raise

# PR5: Escalate relative redirect handling to raise on unsafe relative URLs without leading slash.
Rails.configuration.action_controller.action_on_path_relative_redirect = :raise

# PR6: Stop escaping HTML entities and line separators in JSON responses to match 8.1 defaults.
# Applications that need the previous escaping behavior can set this to true.
Rails.configuration.action_controller.escape_json_responses = false

# ActiveRecord defaults
# Raise an exception when finder methods (first, second, etc.) are used without explicit ordering.
Rails.configuration.active_record.raise_on_missing_required_finder_order_columns = true
