name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' ||  github.actor == 'github-actions[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.6
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
      # if: ${{contains(steps.metadata.outputs.dependency-names, 'my-dependency') && steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        # if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        uses: fastify/github-action-merge-dependabot@v3.6.2
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          use-github-auto-merge: true
        env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}

  # auto-merge:
  #         name: Auto-Merge PRs by Dependabot
  #         needs:
  #             - dependabot
  #         runs-on: ubuntu-latest
  #         permissions:
  #             pull-requests: write
  #             contents: write
  #         steps:
  #           - uses: fastify/github-action-merge-dependabot@v3.6.2
  #             with:
  #                 github-token: ${{ secrets.GITHUB_TOKEN }}
  #                 target: minor

