name: Dependabot Update Gemfile.next.lock
on:
  push:
    branches:
      - dependabot/bundler/tailwindcss-rails-2.7.3
  pull_request:
    # types:
    #   - opened
    #   - reopened
    branches:
      - dependabot/**

permissions:
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Extract Ruby Version
        id: ruby_version
        run: |
          major_minor_version=$(grep -A 1 "RUBY VERSION" Gemfile.next.lock | tail -n 1 | awk '{split($2,a,"[p.]"); print a[1] "." a[2]}')
          echo "MAJOR_MINOR_VERSION=$major_minor_version" >> $GITHUB_ENV
      - name: Setup Ruby 3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.MAJOR_MINOR_VERSION }}
          bundler-cache: true
        env:
          BUNDLE_GEMFILE: Gemfile.next
      # - name: Build next and unit test
      #   env:
      #     RAILS_ENV: test
      #     RAILS_MASTER_KEY: ${{ secrets.RAILS_TEST_KEY }}
      #     CI: true
      #   continue-on-error: false
      #   run: |
      #     # should update dependabot to manage the Gemfile.next.lock
      #     bin/setup-next
      # - name: Install dependencies for Gemfile.next
      #   run: |
      #     bundle install --gemfile=Gemfile.next

      - name: Commit and push updated Gemfile.next.lock
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Gemfile.next.lock
          git commit -m "Update Gemfile.next.lock"
          git push origin ${{ github.head_ref }}
